### ISSUE TITLE
pip install enum34

### ISSUE THREAD

**Issue by TurkicKhan** [leixingyu/autoRigger#3]
How can i do that?

**Comment by leixingyu** [comment]
If you're using a version of Maya that is still using Python 2 (for instance Maya2018), you'll want to install this 'enum34' package in your python environment.
To do that, you can follow: [Maya Offical Guide: Managing Python packages with mayapy and pip](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2022/ENU/Maya-Scripting/files/GUID-72A245EC-CDB4-46AB-BEE0-4BBBF9791627-htm.html) or [PIP user guide](https://pip.pypa.io/en/stable/user_guide/)
