### ISSUE TITLE
What am I doing wrong? ModuleNotFoundError: No module named 'autoRigger' 

### ISSUE THREAD

**Issue by inegvin** [leixingyu/autoRigger#4]
Once I'm trying to run the script 
```
from autoRigger import autoRigger
autoRigger.show()
```

I get this error: 
` # Error: ModuleNotFoundError: file C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py line 142: No module named 'autoRigger' #`

**Comment by leixingyu** [comment]
Can you tell me what directory are you putting tool in? 
It needs to be either in `%USERPROFILE%/Documents/maya/[current maya version]/scripts/` or a path in `PYTHONPATH` env, also the folder name needs to be called `autoRigger`

**Comment by inegvin** [comment]
Ok. Replaced "autoRigger master" folder with "autoRigger". I still have an error but it is slightly different: `# Error: ModuleNotFoundError: file C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py line 142: No module named 'utility' #`
The directory is: C:\Users\Jane\Documents\maya\2022\scripts

**Comment by leixingyu** [comment]
You are missing the 'utility' library, which shouldn't be the case if you download my packaged zip file, instructions here: https://github.com/leixingyu/autoRigger#launch

basically, in this page: https://github.com/leixingyu/autoRigger/releases/tag/v2.0.1 Download and unzip the 'autoRigger.zip', not the source code.
